swagger: "2.0"

info:
  title: TODO service
  description: API for TODO service.
  version: 1.0.0
host: "localhost:8000"
basePath: /
schemes:
  - https
paths:
  /tasks/{id}:
    get:
      summary: Return a list of tasks.
        - application/json
      produces:
        - text/html
      parameters:
        - name: id
          in: path
          description: The task id.
          required: true
          type: integer
      responses:
        200:
          description: OK
        401:
          $ref: "./responses/unauthorized.yaml"
        403:
          $ref: "./responses/forbidden.yaml"
        404:
          $ref: "./responses/notfound.yaml"
        422:
          $ref: "./responses/unprocessable.yaml"
    post:
      summary: Create the task.
      consumes:
        - application/json
      produces:
        - text/html
      parameters:
        - name: id
          in: path
          description: The task id.
          required: true
          type: integer
      responses:
        200:
          description: OK
        401:
          $ref: "./responses/unauthorized.yaml"
        403:
          $ref: "./responses/forbidden.yaml"
        404:
          $ref: "./responses/notfound.yaml"
        422:
          $ref: "./responses/unprocessable.yaml"
    put:
      summary: Update the task.
      consumes:
        - application/json
      produces:
        - text/html
      parameters:
        - name: id
          in: path
          description: The task id.
          required: true
          type: integer
      responses:
        200:
          description: OK
        401:
          $ref: "./responses/unauthorized.yaml"
        403:
          $ref: "./responses/forbidden.yaml"
        404:
          $ref: "./responses/notfound.yaml"
        422:
          $ref: "./responses/unprocessable.yaml"
    delete:
      summary: Delete the task.
      consumes:
        - application/json
      produces:
        - text/html
      parameters:
        - name: id
          in: path
          description: The task id.
          required: true
          type: integer
      responses:
        200:
          description: OK
        401:
          $ref: "./responses/unauthorized.yaml"
        403:
          $ref: "./responses/forbidden.yaml"
        404:
          $ref: "./responses/notfound.yaml"
        422:
          $ref: "./responses/unprocessable.yaml"

  /auth:
    post:
      summary: Authorizate user with credentials.
      consumes:
        - application/json
      produces:
        - text/html
      responses:
        200:
          description: OK
        422:
          $ref: "./responses/unprocessable.yaml"
